# -*- coding: utf-8 -*-
"""Huberman.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BrPINJldMUU19hrLIxmCq5jEweCbAKyd

Data huberman
"""

# =========================
# Import Library
# =========================
import pandas as pd
import matplotlib.pyplot as plt

# =========================
# Load Dataset (tetap 4 kolom)
# =========================
df = pd.read_csv('haberman.csv')
df.columns = ['age', 'year', 'nodes', 'status']

# Kita TIDAK pakai nodes
kolom_numerik = ['age', 'year']

# =========================
# HISTOGRAM
# =========================
for kolom in kolom_numerik:
    plt.figure()
    plt.hist(df[kolom])
    plt.title(f'Histogram {kolom}')
    plt.xlabel(kolom)
    plt.ylabel('Frekuensi')
    plt.show()

# =========================
# BOXPLOT berdasarkan Status Survival
# =========================
for kolom in kolom_numerik:
    df.boxplot(column=kolom, by='status')
    plt.title(f'Boxplot {kolom} berdasarkan Status Survival')
    plt.suptitle('')
    plt.xlabel('')  # hapus tulisan panjang
    plt.ylabel(kolom)
    plt.show()